### ISSUE TITLE
ReferenceError: cb is not defined

### ISSUE THREAD

**Issue by pabloweinx** [choonyme/node-socksftp#2]
I can't figure out what kind of error is being launched when the script is trying to call that undefined "cb" function (I suppose callback, but is not intended to be received in the function declared on connection.js:360:10). 

Can you help me to be able to catch this error? I would code a workaround and propose a pull request if you don't mind. 

The complete error is:

```
ReferenceError: cb is not defined
     at /backend/scripts/ftp_process/node_modules/socksftp/lib/connection.js:360:10
     at finish (/backend/scripts/ftp_process/node_modules/socks-client/lib/socks-client.js:264:17)
     at Socket.<anonymous> (/backend/scripts/ftp_process/node_modules/socks-client/lib/socks-client.js:56:13)
     at Socket.g (events.js:260:16)
     at emitOne (events.js:77:13)
     at Socket.emit (events.js:169:7)
     at TCP._onclose (net.js:477:12)
```

Thank you!

**Comment by choonyme** [comment]
Hi Pablo,

Sorry for the late reply as I was busy. Based on the error, it means it couldn’t create a connection to the SOCKS server. Eg. A SOCKS connection timeout. And the call to cb is supposed to notify you of this error.

CJ
